#markdown: rdiscount
markdown: kramdown
#markdown: redcarpet
highlighter: pygments
safe: false
permalink: /posts/:title.html
exclude:
  - README.md

name: Avoid distractions
url: wangdw2007.github.com
desc: Don't give up

custom:
    category:
        notes: 学习笔记
        write: 随笔
        problems: 遇到问题
    categories:
      - name:  notes
        title: 学习笔记

      - name:  write
        title: 随笔

      - name:  problems
        title: 遇到问题

meta:
    author:
        name: david
        email: wangdw2007@gmail.com
        disqus: wangdw 			                # Disqus缩略标识
        gcse: 002980071478006019237:bcmd-n00ura     # Google自定义搜索标识ID
        github: wangdw2007              			    # GitHub账号
        gravatar: 06a066ffedf35f66f4c5125f7cc0b27a  # Gravatar头像标识

    disqus: disqus.com/embed.js                     # Disqus评论的JS地址
    gapi: http://www.google.com/jsapi               # Google API地址
    gravatar: http://en.gravatar.com/avatar/        # Gravatar头像服务器地址
